### ISSUE TITLE
Modifikacija u Objektno Orjentisano

### ISSUE THREAD

**Issue by skahvedzic** [Samir823/Simple_Array#9]
Molim da ostavite komentar, vezan za pull...

pozic

**Comment by memo91** [comment]
Kakav pull ljudino?

**Comment by skahvedzic** [comment]
pa eto da si povukao izmjene..zahvaljujem

**Comment by memo91** [comment]
mozel se komentarisat kad se zakljuca

**Comment by ivanamd82** [comment]
done

**Comment by ivanamd82** [comment]
jel se vidi com kad je zakljucano

**Comment by skahvedzic** [comment]
moze, moze..sve se moze kad se hoce
